package com.java.oracle.ui;

import com.java.oracle.dao.ApplicationUserDAO;
import com.java.oracle.dao.RoleDAO;
import com.java.oracle.entity.ApplicationUser;
import com.java.oracle.entity.Role;
import com.java.oracle.utils.ApplicationContext;
import com.java.oracle.utils.DatabaseUtil;
import com.java.oracle.utils.ReportUtil;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JDialog;

public class MainApp extends javax.swing.JFrame {

    private RoleDAO roleDAO = new RoleDAO(Role.class);
    private JDialog  logoutDialog;
    /**
     * Creates new form MainApp
     */
    public MainApp(JDialog logoutDialog) {
        this.logoutDialog = logoutDialog;
        initComponents();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                DatabaseUtil.shutdown();
            }
            
        });
        initRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnitNewUser = new javax.swing.JMenuItem();
        mnitUserList = new javax.swing.JMenuItem();
        mnitLogout = new javax.swing.JMenuItem();
        mnuProject = new javax.swing.JMenu();
        mnitNewProject = new javax.swing.JMenuItem();
        mnitProjectList = new javax.swing.JMenuItem();
        mnitProjectRole = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        mnitNewCustomer = new javax.swing.JMenuItem();
        mnitCustomerList = new javax.swing.JMenuItem();
        mnuContract = new javax.swing.JMenu();
        mnitContract = new javax.swing.JMenuItem();
        mnitContractList = new javax.swing.JMenuItem();
        mnitAssignProject = new javax.swing.JMenuItem();
        mnitProjectContractList = new javax.swing.JMenuItem();
        mnuRole = new javax.swing.JMenu();
        mnitNewRole = new javax.swing.JMenuItem();
        mnitRoleList = new javax.swing.JMenuItem();
        mnuReport = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        mnitProjectRunning = new javax.swing.JMenuItem();
        mnitProjectMember = new javax.swing.JMenuItem();
        mnitProjectContract = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnitRevByCus = new javax.swing.JMenuItem();
        mnitRevByProject = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mnitContractRemain = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jToggleButton1.setText("jToggleButton1");

        jToolBar1.setRollover(true);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Management System");

        mnuSystem.setText("System");

        mnitNewUser.setText("New User");
        mnitNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitNewUserActionPerformed(evt);
            }
        });
        mnuSystem.add(mnitNewUser);

        mnitUserList.setText("User List");
        mnitUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitUserListActionPerformed(evt);
            }
        });
        mnuSystem.add(mnitUserList);

        mnitLogout.setText("Logout");
        mnitLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitLogoutActionPerformed(evt);
            }
        });
        mnuSystem.add(mnitLogout);

        jMenuBar1.add(mnuSystem);

        mnuProject.setText("Project");

        mnitNewProject.setText("New Project");
        mnitNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitNewProjectActionPerformed(evt);
            }
        });
        mnuProject.add(mnitNewProject);

        mnitProjectList.setText("Project List");
        mnitProjectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProjectListActionPerformed(evt);
            }
        });
        mnuProject.add(mnitProjectList);

        mnitProjectRole.setText("Project Role");
        mnitProjectRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProjectRoleActionPerformed(evt);
            }
        });
        mnuProject.add(mnitProjectRole);

        jMenuBar1.add(mnuProject);

        mnuCustomer.setText("Customer");

        mnitNewCustomer.setText("New Customer");
        mnitNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitNewCustomerActionPerformed(evt);
            }
        });
        mnuCustomer.add(mnitNewCustomer);

        mnitCustomerList.setText("Customer List");
        mnitCustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCustomerListActionPerformed(evt);
            }
        });
        mnuCustomer.add(mnitCustomerList);

        jMenuBar1.add(mnuCustomer);

        mnuContract.setText("Contract");

        mnitContract.setText("New Contract");
        mnitContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitContractActionPerformed(evt);
            }
        });
        mnuContract.add(mnitContract);

        mnitContractList.setText("Contract List");
        mnitContractList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitContractListActionPerformed(evt);
            }
        });
        mnuContract.add(mnitContractList);

        mnitAssignProject.setText("Assign To Project");
        mnitAssignProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitAssignProjectActionPerformed(evt);
            }
        });
        mnuContract.add(mnitAssignProject);

        mnitProjectContractList.setText("Project Contract List");
        mnitProjectContractList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProjectContractListActionPerformed(evt);
            }
        });
        mnuContract.add(mnitProjectContractList);

        jMenuBar1.add(mnuContract);

        mnuRole.setText("Role");

        mnitNewRole.setText("New Role");
        mnitNewRole.setActionCommand("");
        mnitNewRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitNewRoleActionPerformed(evt);
            }
        });
        mnuRole.add(mnitNewRole);

        mnitRoleList.setText("Role List");
        mnitRoleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitRoleListActionPerformed(evt);
            }
        });
        mnuRole.add(mnitRoleList);

        jMenuBar1.add(mnuRole);

        mnuReport.setText("Report");

        jMenu6.setText("Project");

        mnitProjectRunning.setText("Project Running");
        mnitProjectRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProjectRunningActionPerformed(evt);
            }
        });
        jMenu6.add(mnitProjectRunning);

        mnitProjectMember.setText("Project Member");
        mnitProjectMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProjectMemberActionPerformed(evt);
            }
        });
        jMenu6.add(mnitProjectMember);

        mnitProjectContract.setText("Project Contract");
        mnitProjectContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProjectContractActionPerformed(evt);
            }
        });
        jMenu6.add(mnitProjectContract);

        mnuReport.add(jMenu6);

        jMenu7.setText("Revenue");

        mnitRevByCus.setText("Revenue By Customer");
        mnitRevByCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitRevByCusActionPerformed(evt);
            }
        });
        jMenu7.add(mnitRevByCus);

        mnitRevByProject.setText("Revenue By Project");
        mnitRevByProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitRevByProjectActionPerformed(evt);
            }
        });
        jMenu7.add(mnitRevByProject);

        mnuReport.add(jMenu7);

        jMenu8.setText("Contract");

        mnitContractRemain.setText("Contract Remaining");
        mnitContractRemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitContractRemainActionPerformed(evt);
            }
        });
        jMenu8.add(mnitContractRemain);

        mnuReport.add(jMenu8);

        jMenuBar1.add(mnuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitNewProjectActionPerformed

        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        FunctionPanel functionPanel = new FunctionPanel(dialogUtil);
        dialogUtil.setFunctionPanel(functionPanel);
        // Create project panel
        ProjectPanel projectPanel = new ProjectPanel();
        functionPanel.setMainPanel(projectPanel);
       
        // Display dialog
        dialogUtil.setVisible(true);
        
    }//GEN-LAST:event_mnitNewProjectActionPerformed

    private void mnitProjectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProjectListActionPerformed
        
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        ProjectListPanel projectListPanel = new ProjectListPanel(dialogUtil);
        dialogUtil.setFunctionPanel(projectListPanel);
        // Display dialog
        dialogUtil.setVisible(true);
        
    }//GEN-LAST:event_mnitProjectListActionPerformed

    private void mnitNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitNewCustomerActionPerformed
        
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        FunctionPanel functionPanel = new FunctionPanel(dialogUtil);
        dialogUtil.setFunctionPanel(functionPanel);
        // Create customer panel
        CustomerPanel customerPanel = new CustomerPanel();
        functionPanel.setMainPanel(customerPanel);
       
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitNewCustomerActionPerformed

    private void mnitCustomerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCustomerListActionPerformed
        
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        CustomerListPanel customerListPanel = new CustomerListPanel(dialogUtil);
        dialogUtil.setFunctionPanel(customerListPanel);
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitCustomerListActionPerformed

    private void mnitNewRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitNewRoleActionPerformed
        
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        FunctionPanel functionPanel = new FunctionPanel(dialogUtil);
        dialogUtil.setFunctionPanel(functionPanel);
        // Create role panel
        RolePanel rolePanel = new RolePanel();
        functionPanel.setMainPanel(rolePanel);
       
        // Display dialog
        dialogUtil.setVisible(true);
        
    }//GEN-LAST:event_mnitNewRoleActionPerformed

    private void mnitRoleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitRoleListActionPerformed
        
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        RoleListPanel roleListPanel = new RoleListPanel(dialogUtil);
        dialogUtil.setFunctionPanel(roleListPanel);
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitRoleListActionPerformed

    private void mnitContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitContractActionPerformed
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        FunctionPanel functionPanel = new FunctionPanel(dialogUtil);
        dialogUtil.setFunctionPanel(functionPanel);
        // Create role panel
        ContractPanel contractPanel = new ContractPanel();
        functionPanel.setMainPanel(contractPanel);
       
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitContractActionPerformed

    private void mnitContractListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitContractListActionPerformed

        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        ContractListPanel contractListPanel = new ContractListPanel(dialogUtil);
        dialogUtil.setFunctionPanel(contractListPanel);
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitContractListActionPerformed

    private void mnitNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitNewUserActionPerformed
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        FunctionPanel functionPanel = new FunctionPanel(dialogUtil);
        dialogUtil.setFunctionPanel(functionPanel);
        // Create role panel
        UserPanel userPanel = new UserPanel();
        functionPanel.setMainPanel(userPanel);
       
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitNewUserActionPerformed

    private void mnitUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitUserListActionPerformed
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        ApplicationUserListPanel applicationUserListPanel = new ApplicationUserListPanel(dialogUtil);
        dialogUtil.setFunctionPanel(applicationUserListPanel);
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitUserListActionPerformed

    private void mnitProjectRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProjectRoleActionPerformed
        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        ProjectRolePanel projectRolePanel = new ProjectRolePanel(dialogUtil);
        dialogUtil.setFunctionPanel(projectRolePanel);
        // Display dialog
        dialogUtil.setVisible(true);
    }//GEN-LAST:event_mnitProjectRoleActionPerformed

    private void mnitAssignProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitAssignProjectActionPerformed

        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        FunctionPanel functionPanel = new FunctionPanel(dialogUtil);
        dialogUtil.setFunctionPanel(functionPanel);
        // Create role panel
        ProjectContractPanel projectContractPanel = new ProjectContractPanel();
        functionPanel.setMainPanel(projectContractPanel);
       
        // Display dialog
        dialogUtil.setVisible(true);
        
    }//GEN-LAST:event_mnitAssignProjectActionPerformed

    private void mnitProjectContractListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProjectContractListActionPerformed

        // Create dialog
        DialogUtil dialogUtil = new DialogUtil();
        // Create functional panel
        ProjectContractListPanel projectContractListPanel = new ProjectContractListPanel(dialogUtil);
        dialogUtil.setFunctionPanel(projectContractListPanel);
        // Display dialog
        dialogUtil.setVisible(true);
        
    }//GEN-LAST:event_mnitProjectContractListActionPerformed

    private void mnitProjectRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProjectRunningActionPerformed
        
        ReportUtil.viewReport(ReportUtil.ReportType.PROJECT);
        
    }//GEN-LAST:event_mnitProjectRunningActionPerformed

    private void mnitLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitLogoutActionPerformed

        if(logoutDialog != null) {
            this.setVisible(false);
            ApplicationContext.setLoggedinUser(null);
            logoutDialog.setVisible(true);
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_mnitLogoutActionPerformed

    private void mnitProjectContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProjectContractActionPerformed
        ReportUtil.viewReport(ReportUtil.ReportType.PROJECT_CONTRACT);
    }//GEN-LAST:event_mnitProjectContractActionPerformed

    private void mnitProjectMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProjectMemberActionPerformed
        ReportUtil.viewReport(ReportUtil.ReportType.PROJECT_MEMBER);
    }//GEN-LAST:event_mnitProjectMemberActionPerformed

    private void mnitRevByCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitRevByCusActionPerformed

        ReportUtil.viewReport(ReportUtil.ReportType.REV_CUSTOMER);
    }//GEN-LAST:event_mnitRevByCusActionPerformed

    private void mnitRevByProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitRevByProjectActionPerformed

        ReportUtil.viewReport(ReportUtil.ReportType.REV_PROJECT);
        
    }//GEN-LAST:event_mnitRevByProjectActionPerformed

    private void mnitContractRemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitContractRemainActionPerformed

        ReportUtil.viewReport(ReportUtil.ReportType.CONTRACT_REMAIN);
    }//GEN-LAST:event_mnitContractRemainActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApplicationUserDAO applicationUserDAO = new ApplicationUserDAO(ApplicationUser.class);
                List<ApplicationUser> list = applicationUserDAO.selectAll();
                if(list == null) {
                    ApplicationUser applicationUser = new ApplicationUser();
                    applicationUser.setAccount("admin");
                    applicationUser.setName("Admin");
                    applicationUser.setActive(true);
                    applicationUser.setAdmin(true);
                    applicationUser.setPassword("admin");
                    applicationUserDAO.save(applicationUser);
                }
                final DialogUtil dialogUtil = new DialogUtil();
                dialogUtil.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        DatabaseUtil.shutdown();
                        System.exit(0);
                    }
                    
                });
                dialogUtil.setSize(new Dimension(450, 250));
                LoginForm form = new LoginForm();
                form.setLoginAction(new LoginForm.LoginAction() {
                    @Override
                    public void onSuccess(ApplicationUser applicationUser) {
                        ApplicationContext.setLoggedinUser(applicationUser);
                        dialogUtil.dispose();
                        new MainApp(dialogUtil).setVisible(true);
                    }
                });
                dialogUtil.setFunctionPanel(form);
                dialogUtil.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnitAssignProject;
    private javax.swing.JMenuItem mnitContract;
    private javax.swing.JMenuItem mnitContractList;
    private javax.swing.JMenuItem mnitContractRemain;
    private javax.swing.JMenuItem mnitCustomerList;
    private javax.swing.JMenuItem mnitLogout;
    private javax.swing.JMenuItem mnitNewCustomer;
    private javax.swing.JMenuItem mnitNewProject;
    private javax.swing.JMenuItem mnitNewRole;
    private javax.swing.JMenuItem mnitNewUser;
    private javax.swing.JMenuItem mnitProjectContract;
    private javax.swing.JMenuItem mnitProjectContractList;
    private javax.swing.JMenuItem mnitProjectList;
    private javax.swing.JMenuItem mnitProjectMember;
    private javax.swing.JMenuItem mnitProjectRole;
    private javax.swing.JMenuItem mnitProjectRunning;
    private javax.swing.JMenuItem mnitRevByCus;
    private javax.swing.JMenuItem mnitRevByProject;
    private javax.swing.JMenuItem mnitRoleList;
    private javax.swing.JMenuItem mnitUserList;
    private javax.swing.JMenu mnuContract;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuProject;
    private javax.swing.JMenu mnuReport;
    private javax.swing.JMenu mnuRole;
    private javax.swing.JMenu mnuSystem;
    // End of variables declaration//GEN-END:variables

    private void initRole() {
        ApplicationUser loggedinUser = ApplicationContext.getLoggedinUser();
        Boolean admin = loggedinUser.isAdmin();
        if(admin) {
            mnitNewUser.setVisible(true);
            mnitUserList.setVisible(true);
        } else {
            mnitNewUser.setVisible(false);
            mnitUserList.setVisible(false);
        }
        if(ApplicationUser.ROLE_PROJECT_ADMIN.equals(loggedinUser.getRoleCode())) {
            mnuProject.setVisible(true);
            mnuContract.setVisible(true);
            mnuCustomer.setVisible(true);
            mnuReport.setVisible(true);
            mnuRole.setVisible(true);
        } else if(ApplicationUser.ROLE_PROJECT_MEMBER.equals(loggedinUser.getRoleCode())) {
            mnuProject.setVisible(true);
            mnuContract.setVisible(false);
            mnuCustomer.setVisible(false);
            mnuReport.setVisible(false);
            mnuRole.setVisible(false);
        } else if(ApplicationUser.ROLE_REPORTER.equals(loggedinUser.getRoleCode())) {
            mnuProject.setVisible(false);
            mnuContract.setVisible(false);
            mnuCustomer.setVisible(false);
            mnuReport.setVisible(true);
            mnuRole.setVisible(false);
        }
    }
}
