package com.java.oracle.ui;

import com.java.oracle.dao.ApplicationUserDAO;
import com.java.oracle.dao.CustomerDAO;
import com.java.oracle.dao.ProjectDAO;
import com.java.oracle.entity.ApplicationUser;
import com.java.oracle.entity.Customer;
import com.java.oracle.entity.Project;
import com.java.oracle.utils.DateUtils;
import com.java.oracle.vo.ComboItem;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class ProjectPanel extends AbstractPanel<Project> {

    private ProjectDAO projectDAO;
    private CustomerDAO customerDAO;
    private ApplicationUserDAO applicationUserDAO;
    
    private DefaultComboBoxModel cboCustomerModel;
    private DefaultComboBoxModel cboUserModel;

    /**
     * Creates new form ProjectPanel
     */
    public ProjectPanel() {
        projectDAO = new ProjectDAO(Project.class);
        customerDAO = new CustomerDAO(Customer.class);
        applicationUserDAO = new ApplicationUserDAO(ApplicationUser.class);
        setAbstractDAO(projectDAO);
        initComponents();
        cboCustomerModel = new DefaultComboBoxModel();
        cboUserModel = new DefaultComboBoxModel();
        cboCustomer.setModel(cboCustomerModel);
        cboProjectLead.setModel(cboUserModel);
        initCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProjectCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboCustomer = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboProjectLead = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROJECT");

        jLabel2.setText("Project Code");

        jLabel3.setText("Project Name");

        jLabel4.setText("Start Date");

        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        jLabel5.setText("End Date");

        jLabel6.setText("Customer");

        cboCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Leader");

        cboProjectLead.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Description");

        jLabel9.setText("Status");

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "On-going", "Closed", "Cancel" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProjectCode)
                    .addComponent(txtProjectName)
                    .addComponent(txtStartDate)
                    .addComponent(txtEndDate)
                    .addComponent(cboCustomer, 0, 416, Short.MAX_VALUE)
                    .addComponent(cboProjectLead, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescription)
                    .addComponent(cboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboProjectLead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCustomer;
    private javax.swing.JComboBox<String> cboProjectLead;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtProjectCode;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    @Override
    public Project prepareData() {
        if (bean == null) {
            bean = new Project();
            bean.setStatus("Open");
        }
        bean.setProjectCode(txtProjectCode.getText());
        bean.setProjectName(txtProjectName.getText());
        bean.setStartDate(DateUtils.parseFromString(txtStartDate.getText()));
        bean.setEndDate(DateUtils.parseFromString(txtEndDate.getText()));
        bean.setCustomerId(((ComboItem)cboCustomer.getSelectedItem()).getId());
        bean.setProjectLead(((ComboItem)cboProjectLead.getSelectedItem()).getValue());
        bean.setDescription(txtDescription.getText());
        bean.setStatus(cboStatus.getSelectedItem().toString());
        return bean;
    }

    @Override
    public boolean validateData() {
        if(txtProjectCode.getText() == null || txtProjectCode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Project code is mandatory!");
            txtProjectCode.requestFocus();
            return false;
        }
        if(txtProjectName.getText() == null || txtProjectName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Project name is mandatory!");
            txtProjectName.requestFocus();
            return false;
        }
        if(cboProjectLead.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Project lead is mandatory!");
            return false;
        }
        
        if(cboCustomer.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Customer is mandatory!");
            return false;
        }
        if(txtStartDate.getText() != null || !txtStartDate.getText().isEmpty()) {
            if (DateUtils.parseFromString(txtStartDate.getText()) == null) {
                txtStartDate.requestFocus();
                return false;
            }
        }
        if(txtEndDate.getText() != null || !txtEndDate.getText().isEmpty()) {
            if (DateUtils.parseFromString(txtEndDate.getText()) == null) {
                txtEndDate.requestFocus();
                return false;
            }
        }
        return true;
    }

    @Override
    public void loadData() {
        if(bean != null) {
            txtProjectCode.setText(bean.getProjectCode());
            txtProjectName.setText(bean.getProjectName());
            txtStartDate.setText(DateUtils.parseFromDate(bean.getStartDate()));
            txtEndDate.setText(DateUtils.parseFromDate(bean.getEndDate()));
            if(bean.getCustomerId() != null){
                Customer c = customerDAO.getById(bean.getCustomerId());
                if(c != null){
                    for(int i = 0; i < cboCustomerModel.getSize(); i++) {
                        if(c.getId().equals(((ComboItem)cboCustomerModel.getElementAt(i)).getId())) {
                            cboCustomer.setSelectedIndex(i);
                            break;
                        }
                    }
                }
            }
            if(bean.getStatus() != null) {
                cboStatus.setSelectedItem(bean.getStatus());
            }
            ApplicationUser user = applicationUserDAO.getByCode(bean.getProjectLead());
            if(user != null){
                for(int i = 0; i < cboUserModel.getSize(); i++) {
                    if(user.getId().equals(((ComboItem)cboUserModel.getElementAt(i)).getId())) {
                        cboProjectLead.setSelectedIndex(i);
                        break;
                    }
                }
            }
            txtDescription.setText(bean.getDescription());
        }
    }

    private void initCombobox() {
        List<Customer> customers = customerDAO.selectAll();
        if(customers != null && !customers.isEmpty()) {
            for(Customer c:customers) {
                cboCustomerModel.addElement(new ComboItem(c.getId(), c.getCustomerCode()));
            }
        }
        
        List<ApplicationUser> applicationUsers = applicationUserDAO.selectAll();
        if(applicationUsers != null && !applicationUsers.isEmpty()) {
            for(ApplicationUser a:applicationUsers) {
                cboUserModel.addElement(new ComboItem(a.getId(), a.getAccount()));
            }
        }
    }
}
